---
- name: Merge sensu_go_community_repos_overrides w/ defaults
  set_fact:
    sensu_go_final_community_repos: "{{ sensu_go_community_repos | combine(sensu_go_community_repos_overrides, recursive=True) }}"

- name: Configure Sensu Go Community GPG key in the RPM keyring
  rpm_key:
    key: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['gpgkey'] }}"
    state: present
  register: sensu_go_import_community_key

- name: Configure Sensu Go Community yum repos
  yum_repository:
    file: sensu_go_community
    name: sensu_go_community
    description: packagecloud.io mirrors for Sensu Go Community RPMs
    baseurl: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['rpm'] }}"
    gpgcheck: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['gpgcheck'] }}"
    gpgkey: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['gpgkey'] }}"
    repo_gpgcheck: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['repo_gpgcheck'] }}"
    sslverify: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['sslverify'] }}"
    metadata_expire: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['metadata_expire'] }}"
  when: sensu_go_final_community_repos[ansible_pkg_mgr]['rpm'] is defined

- name: Configure Sensu Go Community yum source repos
  yum_repository:
    file: sensu_go_community
    name: sensu_go_community-source
    description: packagecloud.io mirrors for Sensu Go Community Source RPMS
    baseurl: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['rpm-src'] }}"
    gpgkey: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['gpgkey'] }}"
    gpgcheck: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['gpgcheck'] }}"
    repo_gpgcheck: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['repo_gpgcheck'] }}"
    sslverify: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['sslverify'] }}"
    metadata_expire: "{{ sensu_go_final_community_repos[ansible_pkg_mgr]['metadata_expire'] }}"
  when: sensu_go_final_community_repos[ansible_pkg_mgr]['rpm-src'] is defined

# HACK: https://github.com/ansible/ansible/issues/20711#issuecomment-306260869
# Can be removed once we're running w/ a version of Ansible that has https://github.com/ansible/ansible/pull/35989
# Update: Looks like only CentOS 6 requires this hack
- name: Make yum cache to import Sensu Go Community GPG keys # noqa 503 - Order matters for this task
  command: "yum -q makecache -y --disablerepo='*' --enablerepo='{{ item }}'"
  args:
    warn: false
  when: sensu_go_import_community_key.changed
  with_items:
    - sensu_go_community
    - sensu_go_community-source
