---
scenario:
  name: amazonlinux
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: amazonlinux-1
    image: dokken/amazonlinux
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
  - name: amazonlinux-2
    image: dokken/amazonlinux-2
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: yaml,timer,profile_tasks
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      poll_interval: 3
      forks: 100
    connection:
      pipelining: true
  playbooks:
    prepare: ../shared/prepare.yml
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/playbook.yml
    verify: ../shared/verify.yml
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      amazonlinux-1:
        sensu_go_repos_overrides:
          yum:
            rpm: https://packagecloud.io/sensu/stable/el/6/x86_64
            rpm-src: https://packagecloud.io/sensu/stable/el/6/SRPMS
        inspec_version: el6
      amazonlinux-2:
        sensu_go_repos_overrides:
          yum:
            rpm: https://packagecloud.io/sensu/stable/el/7/x86_64
            rpm-src: https://packagecloud.io/sensu/stable/el/7/SRPMS
        inspec_version: el7
verifier:
  name: inspec
  directory: ../shared/tests/
  lint:
    name: rubocop
